### ISSUE TITLE
Syntax breaks after regular expression: /\/\*([\s\S]*?)\*\//

### ISSUE THREAD

**Issue by evandrocoan** [lark-parser/lark_syntax#4]
![image](https://user-images.githubusercontent.com/5332158/44537467-46bf7f00-a6d5-11e8-8d12-73d57678c344.png)

```regex
// General non terminal constructs
free_input_string: /(\\{|\\}|[^\n{}])+/

SINGLE_LINE_COMMENT: /(\#|\/\/)[^\n]*/
// MULTI_LINE_COMMENT: /\/\*([\s\S]*?)\*\//

NEWLINE: (CR? LF)+
_NEWLINE: ( /\r?\n[\t ]*/ | SINGLE_LINE_COMMENT )+
INTEGER: "0".."9"
```

Commenting out the line fixes it:
![image](https://user-images.githubusercontent.com/5332158/44537496-6060c680-a6d5-11e8-9ceb-b38f9ad41768.png)

**Comment by danmou** [comment]
Should be fixed now.

**Comment by deli73** [comment]
this is still broken on our end? are you sure you actually fixed it
![image](https://github.com/lark-parser/lark_syntax/assets/2362969/9c61fe6a-b339-449d-b10f-f4dae3407dff)

**Comment by danmou** [comment]
@deli73 this seems to be a different issue. I don't have the bandwidth to look into it myself but PRs are welcome. As a workaround I think you could turn the comment pattern into a single regex:
```
COMMENT: /\/\/[^\n]*/
```

**Comment by deli73** [comment]
@danmou this still breaks it...?
![image](https://github.com/lark-parser/lark_syntax/assets/2362969/edf1cee5-22a8-4fa0-8617-9981ee35ce22)
does it not work on sublime text 4 or something

**Comment by danmou** [comment]
Hmm ok, not sure why that is, sorry. I'm personally not using Lark anymore and don't have the time to investigate, but please share if you find out anything.
